Repository SAP-samples/btp-setup-automator, pull requests merged in 2023-04, with the labels that each got.

#479 typo in overview
  docs/OVERVIEW.md
Labels: documentation, available in dev

#484 update link checker to update existing issues
  .github/workflows/links-watcher-cron.yml
Labels: enhancement

#487 [NoRef-0] allow special characters for cf user password
  libs/python/helperCommandExecution.py
Labels: bug

#489 update CF CLI to version 8.6.1
  config/Dockerfile
Labels: dependencies

#492 Update years in docu
  .reuse/dep5
  README.md
Labels: documentation

#495 Pin platform for Mac M1/M2 support
  config/Dockerfile
Labels: bug
