Repository SAP-samples/btp-setup-automator, pull requests merged in 2023-03, with the labels that each got.

#450 Tackle "plan not found" issues
  libs/python/btp_cli.py
  libs/python/helperArgParser.py
  libs/python/helperCommandExecution.py
  libs/python/helperEnvBTP.py
  libs/python/helperEnvCF.py
  libs/python/helperEnvKyma.py
  libs/python/helperEnvironments.py
  libs/python/helperGenerator.py
  libs/python/helperGeneric.py
  libs/python/helperJson.py
  libs/python/helperLog.py
  libs/python/helperRolesAndUsers.py
  libs/python/helperServiceInstances.py
  libs/python/helperYaml.py
Labels: bug

#452 App subscriptions with parameters
  libs/python/btp_cli.py
  libs/python/helperEnvCF.py
  libs/python/helperEnvironments.py
Labels: enhancement

#453 implement proper handling of appName for apps
  libs/python/btp_cli.py
  libs/python/helperCommandExecution.py
  libs/python/helperJson.py
Labels: bug

#457 Native HANA consumption
  usecases/released/discoverycenter/3638-kyma-multitenant/parameters.json
  usecases/released/discoverycenter/3638-kyma-multitenant/usecase-customer-template.json
  usecases/released/discoverycenter/3638-kyma-multitenant/usecase.json
  usecases/released/discoverycenter/3999-kyma-day2-operations/README.md
  usecases/released/discoverycenter/3999-kyma-day2-operations/parameters.json
  usecases/released/discoverycenter/3999-kyma-day2-operations/usecase-customer-template.json
  usecases/released/discoverycenter/3999-kyma-day2-operations/usecase.json
  usecases/released/discoverycenter/4000-kyma-identity-management/parameters.json
  usecases/released/discoverycenter/4000-kyma-identity-management/usecase-customer-template.json
  usecases/released/discoverycenter/4000-kyma-identity-management/usecase.json
Labels: enhancement

#456 feat: additional parameter files
  libs/python/btp_cli.py
  libs/python/helperEnvBTP.py
Labels: enhancement

#458 Increase timeouts env plans
  libs/python/helperEnvCF.py
  libs/python/helperEnvironments.py
Labels: enhancement

#459 Use cases for SAP Build Apps Setup and DSAG Technology Days 2023 Demo
  usecases/other/discoverycenter/3774-taskcenter/README.md
  usecases/other/discoverycenter/3774-taskcenter/account-setup.md
  usecases/other/discoverycenter/3774-taskcenter/parameters.json
  usecases/other/discoverycenter/3774-taskcenter/pics/create_destination.png
  usecases/other/discoverycenter/3774-taskcenter/pics/destination_details.png
  usecases/other/discoverycenter/3774-taskcenter/pics/destination_from_service_instance.png
  usecases/other/discoverycenter/3774-taskcenter/pics/destination_from_service_instance_name.png
  usecases/other/discoverycenter/3774-taskcenter/usecase.json
  usecases/released/dsag/2022-technologydays/README.md
  usecases/released/dsag/2022-technologydays/parameters.json
  usecases/released/dsag/2022-technologydays/usecase.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/README.md
  usecases/released/dsag/2023-technologydays/vt034_landscape/github_action_samples/landscape_cleanup.yml
  usecases/released/dsag/2023-technologydays/vt034_landscape/github_action_samples/landscape_setup.yml
  usecases/released/dsag/2023-technologydays/vt034_landscape/hr/dev/parameters.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/hr/dev/usecase.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/hr/prod/parameters.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/hr/prod/usecase.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/hr/test/parameters.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/hr/test/usecase.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/it/dev/parameters.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/it/dev/usecase.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/it/prod/parameters.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/it/prod/usecase.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/it/test/parameters.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/it/test/usecase.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/sales/dev/parameters.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/sales/dev/usecase.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/sales/prod/parameters.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/sales/prod/usecase.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/sales/test/parameters.json
  usecases/released/dsag/2023-technologydays/vt034_landscape/sales/test/usecase.json
  usecases/released/sap-build-apps/README.md
  usecases/released/sap-build-apps/github_action_samples/btpsa_sap_build_app.yml
  usecases/released/sap-build-apps/step1_parameters.json
  usecases/released/sap-build-apps/step1_usecase.json
  usecases/released/sap-build-apps/step2_parameters.json
  usecases/released/sap-build-apps/step2_usecase.json
  usecases/released/sap-build-apps/step3_parameters.json
  usecases/released/sap-build-apps/step3_usecase.json
Labels: documentation, enhancement

#463 App name fix
  libs/python/btp_cli.py
Labels: bug

#466 Update version of BTP CLI
  config/Dockerfile
Labels: dependencies

#467 Update UseCase file for btp-resilient-apps repo - event mesh changes + entitleonly param usage
  usecases/released/build_resilient_apps_free_tier.json
Labels: bug

#470 Fix NoneType Error during app subscription
  libs/python/btp_cli.py
Labels: bug

#472 Read subaccount domain from existing subaccount
  libs/python/btp_cli.py
Labels: bug

#473 Fix for issue 471 - non-interactive authentication
  libs/python/btp_cli.py
  libs/python/helperCommandExecution.py
Labels: bug

#468 Enhancement of role collection assignment with custom IdP
  config/templates/libs/BTPSA-USECASE.json
  libs/btpsa-usecase.json
  libs/python/helperRolesAndUsers.py
Labels: enhancement

#477 PR for 3586-s4hana-kyma-mission
  usecases/released/discoverycenter/3586-s4hana-kyma/README.md
  usecases/released/discoverycenter/3586-s4hana-kyma/parameters.json
  usecases/released/discoverycenter/3586-s4hana-kyma/usecase.json
Labels: enhancement

#478 Enhanced documentation
  README.md
Labels: documentation
