Repository SAP-samples/btp-setup-automator, pull requests merged in 2023-02, with the labels that each got.

#419 removed arm build
  .github/workflows/docker-release-build-and-push.yml
  config/Dockerfile
  docs/BASIC_SETUP.md
  docs/README.md
  usecases/other/discoverycenter/3774-taskcenter/README.md
  usecases/other/dsag/2022-technologydays/README.md
  usecases/released/discoverycenter/3239-customui/README.md
  usecases/released/discoverycenter/3384-ecc-extension/README.md
  usecases/released/discoverycenter/3586-s4hana-kyma/README.md
  usecases/released/discoverycenter/3638-kyma-multitenant/README.md
  usecases/released/discoverycenter/3769-s4hana-addon-extension/README.md
  usecases/released/discoverycenter/3774-taskcenter/README.md
  usecases/released/discoverycenter/3999-kyma-day2-operations/README.md
  usecases/released/discoverycenter/4000-kyma-identity-management/README.md
  usecases/released/discoverycenter/4064-cap-saas-cf/README.md
Labels: bug

#429 Introduction of devcontainer and GitHub Codespaces for easier execution of btpsa
  .devcontainer/dev/devcontainer.json
  .devcontainer/stable/devcontainer.json
  .vscode/settings.json
  docs/BASIC_SETUP.md
  docs/README.md
  docs/pics/command-palette-devcontainer.png
  docs/pics/devcontainer-config-options.png
  docs/pics/open-in-remote-window.png
Labels: enhancement

#431 Issue 430
  libs/python/helperEnvBTP.py
  libs/python/helperServiceInstances.py
Labels: bug

#435 GitHub Codespace Badges
  README.md
Labels: enhancement

#438 fix url issue for codespaces
  README.md
Labels: bug

#439 PR for btpsa-v1.5.1
  README.md
Labels: bug

#441 Devcontainer dev
  .devcontainer/dev/devcontainer.json
Labels: bug

#443 Issue 442
  config/templates/libs/BTPSA-USECASE.json
  libs/btpsa-usecase.json
  libs/python/btp_cli.py
  libs/python/helperCommandExecution.py
  libs/python/helperServiceInstances.py
Labels: bug

#444 fix issue when deleting sapbtp services
  libs/python/helperEnvBTP.py
Labels: bug

#446 Exit if instance cant create
  libs/python/btp_cli.py
Labels: bug

#447 btpsa-v1.5.2
  .devcontainer/dev/devcontainer.json
  .github/workflows/links-watcher-cron.yml
  config/templates/libs/BTPSA-USECASE.json
  docs/generated/btpsa-usecase-properties-services-items-allof-1-then-allof-23-then-allof-0-then-properties-parameters.md
  docs/generated/btpsa-usecase-properties-services-items-allof-1-then-allof-23-then-allof-1-then-properties-parameters.md
  docs/generated/btpsa-usecase-properties-services-items-allof-1-then-allof-85-then-allof-0-then.md
  docs/generated/btpsa-usecase-properties-services-items-allof-1-then-allof-85-then-allof-1-then.md
  docs/generated/btpsa-usecase-properties-services-items-allof-2-then-allof-15-then-allof-0-then.md
  docs/generated/btpsa-usecase-properties-services-items-properties-amount-to-be-used-for-the-service.md
  docs/generated/btpsa-usecase-properties-services-items.md
  libs/btpsa-usecase.json
  libs/python/btp_cli.py
  libs/python/helperCommandExecution.py
  libs/python/helperEnvBTP.py
  libs/python/helperServiceInstances.py
Labels: bug, documentation, dependencies
